// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0dbApYo-YnivXZjnJYz4FQG3vvtM4z7A',
    appId: '1:231310346808:web:a81a429a38b9abde4c34cd',
    messagingSenderId: '231310346808',
    projectId: 'evently-126e5',
    authDomain: 'evently-126e5.firebaseapp.com',
    storageBucket: 'evently-126e5.firebasestorage.app',
    measurementId: 'G-Z8VYQ8KPLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh3zmG7UXT3MtR5doFmxqBbvi0HVCcFoU',
    appId: '1:231310346808:android:d423b490bc41bc784c34cd',
    messagingSenderId: '231310346808',
    projectId: 'evently-126e5',
    storageBucket: 'evently-126e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhXGsxX6JmXTqpZLRaGHmhgGR12QPzdO0',
    appId: '1:231310346808:ios:213a968889425c4d4c34cd',
    messagingSenderId: '231310346808',
    projectId: 'evently-126e5',
    storageBucket: 'evently-126e5.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

}